### ISSUE TITLE
Building RMF in RHEL 8

### ISSUE THREAD

**Issue by cwrx777** [open-rmf/rmf#152] opened 2022-05-04 08:27 UTC
Hi, 
is building and running RMF in RHEL 8 currently supported?

I tried the main and rel 21.09 branch and encountered issues such as missing dependencies on Eigen/Geometry for packages such as rmf_battery, rmf_traffic_ros.

**Comment by marcoag** [comment] 2022-05-05 06:49
Hi,

Most `Open-RMF` packages should build in `RHEL 8`. Specifically Eigen/Geometry seems to be there for those packages that you've mentioned:

- Eigen: https://github.com/ros/rosdistro/blob/076d202447d344ff83a92cab535fcf078370cb6a/rosdep/base.yaml#L878

And you can see the package in RHEL 8 includes Geometry: https://centos.pkgs.org/8/centos-powertools-x86_64/eigen3-devel-3.3.4-6.el8.noarch.rpm.html

- The only ohter related package I can see is `eigen_cmake_module` which is also there in the latest `ROS2` distro: https://github.com/ros/rosdistro/blob/076d202447d344ff83a92cab535fcf078370cb6a/rolling/distribution.yaml#L795

It would help if you are more specific about what "issues" you're encountering. Maybe post the output of the error and steps to reproduce?

As a side note, please use the discussions when asking questions instead of opening an issue.

**Comment by cwrx777** [comment] 2022-05-10 03:55
Hi,
I've created the discussion [here](https://github.com/open-rmf/rmf/discussions/154).

**Comment by marcoag** [comment] 2022-05-10 04:14
Thanks will close this then and follow up there.

**Closed by marcoag** 2022-05-10 04:14 UTC
