### ISSUE TITLE
[Other issue]: could not install ros humble dependencies

### ISSUE THREAD

**Issue by MohammedMuthuFasil** [open-rmf/rmf#483] opened 2024-06-20 07:52 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

**rosdep install --from-paths src --ignore-src --rosdistro humble -yI try to install dependecies using this** "" but i got thos error like **"ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rmf_demos_gz: Cannot locate rosdep definition for [gz_sim_vendor]
rmf_building_sim_gz_plugins: Cannot locate rosdep definition for [gz_transport_vendor]
rmf_building_map_tools: Cannot locate rosdep definition for [gz_fuel_tools_vendor]
rmf_robot_sim_gz_plugins: Cannot locate rosdep definition for [gz_transport_vendor]**
" But humble has no available for this installation packages so how to build my ros-humble-rmf packages

**Comment by aaronchongth** [comment] 2024-06-20 08:42
duplicate of https://github.com/open-rmf/rmf/issues/482

**Comment by aaronchongth** [comment] 2024-06-20 08:44
are you sure your packages are on `humble` branches?
Can you post the contents of the `export.repos` file that gets exported from this command

```
vcs export src > export.repos
```

**Closed** 2024-06-24 05:28 UTC
