### ISSUE TITLE
[Bug]: Launching office world, gazebo GUI not loaded while rviz is ok

### ISSUE THREAD

**Issue by Steven-NYP** [open-rmf/rmf#378] opened 2023-07-19 06:39 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

2.3.0

### ROS distribution

Humble

### ROS installation type

Source build

### Description of the bug

Using the command
```
ros2 launch rmf_demos_gz_classic office.launch.xml server_uri:="ws://localhost:7878"
``` 
Rviz started succcessfully however Gazebo reeceived the following response

![image](https://github.com/open-rmf/rmf/assets/37668174/a6ddb56b-edfc-4a95-99c9-3487895b4a0a)

Terminal showed the following

```
~$ ros2 launch rmf_demos_gz office.launch.xml server_uri:="ws://localhost:7878/_internal"
[INFO] [launch]: All log files can be found below /home/steven/.ros/log/2023-07-19-14-29-25-082333-steven-ubuntu-137670
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rmf_traffic_schedule-1]: process started with pid [137671]
[INFO] [rmf_traffic_blockade-2]: process started with pid [137673]
[INFO] [building_map_server-3]: process started with pid [137675]
[INFO] [schedule_visualizer_node-4]: process started with pid [137677]
[INFO] [fleetstates_visualizer_node-5]: process started with pid [137679]
[INFO] [rmf_visualization_building_systems-6]: process started with pid [137681]
[INFO] [navgraph_visualizer_node-7]: process started with pid [137683]
[INFO] [floorplan_visualizer_node-8]: process started with pid [137685]
[INFO] [obstacle_visualizer_node-9]: process started with pid [137687]
[INFO] [rviz2-10]: process started with pid [137689]
[INFO] [door_supervisor-11]: process started with pid [137691]
[INFO] [lift_supervisor-12]: process started with pid [137693]
[INFO] [rmf_task_dispatcher-13]: process started with pid [137695]
[INFO] [simple_api_server-14]: process started with pid [137697]
[INFO] [fleet_manager-15]: process started with pid [137699]
[INFO] [fleet_adapter-16]: process started with pid [137701]
[INFO] [ign-17]: process started with pid [137703]
[INFO] [parameter_bridge-18]: process started with pid [137705]
[parameter_bridge-18] [ros_ign_bridge] is deprecated! Redirecting to use [ros_gz_bridge] instead!
[parameter_bridge-18] 
[rviz2-10] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[fleetstates_visualizer_node-5] [INFO] [1689748166.726587046] [fleet_states_visualizer]: Configuring fleet_states_visualizer...
[fleetstates_visualizer_node-5] [INFO] [1689748166.726787426] [fleet_states_visualizer]: Setting parameter initial_map_name to L1
[fleetstates_visualizer_node-5] [INFO] [1689748166.726846307] [fleet_states_visualizer]: Setting parameter fleet_state_nose_scale to 0.500000
[fleetstates_visualizer_node-5] [INFO] [1689748166.735547169] [fleet_states_visualizer]: Running fleet_states_visualizer...
[rmf_task_dispatcher-13] ~Initializing Dispatcher Node~
[obstacle_visualizer_node-9] [INFO] [1689748166.740804640] [rmf_obstacle_visualizer]: Beginning RMF obstacle visualizer node
[rmf_task_dispatcher-13] [INFO] [1689748166.767338255] [rmf_dispatcher_node]:  Declared Time Window Param as: 2.000000 secs
[rmf_task_dispatcher-13] [INFO] [1689748166.768447522] [rmf_dispatcher_node]:  Declared Terminated Tasks Max Size Param as: 100
[rmf_task_dispatcher-13] [INFO] [1689748166.769351710] [rmf_dispatcher_node]:  Declared publish_active_tasks_period as: 2 secs
[rmf_task_dispatcher-13] [INFO] [1689748166.770006200] [rmf_dispatcher_node]:  Use timestamp with task_id: false
[rmf_task_dispatcher-13] [INFO] [1689748166.775360017] [rmf_dispatcher_node]: Starting task dispatcher node
[rmf_traffic_schedule-1] [INFO] [1689748166.778319930] [rmf_traffic_schedule_primary]: Successfully loaded logfile .rmf_schedule_node.yaml 
[navgraph_visualizer_node-7] [INFO] [1689748166.778365795] [navgraph_visualizer]: Setting parameter initial_map_name to L1
[navgraph_visualizer_node-7] [INFO] [1689748166.779755836] [navgraph_visualizer]: Setting parameter lane_width to 0.500000
[navgraph_visualizer_node-7] [INFO] [1689748166.780435183] [navgraph_visualizer]: Setting parameter lane_transparency to 0.600000
[navgraph_visualizer_node-7] [INFO] [1689748166.781105767] [navgraph_visualizer]: Setting parameter waypoint_scale to 1.300000
[navgraph_visualizer_node-7] [INFO] [1689748166.781545317] [navgraph_visualizer]: Setting parameter text_scale to 0.700000
[rmf_traffic_schedule-1] [INFO] [1689748166.782617998] [rmf_traffic_schedule_primary]: Set up heartbeat on /rmf_traffic/heartbeat with liveliness lease duration of 10000 ms and deadline of 10000 ms
[schedule_visualizer_node-4] [INFO] [1689748166.786702487] [schedule_visualizer_node]: Setting parameter rate to 10.000000
[schedule_visualizer_node-4] [INFO] [1689748166.787250529] [schedule_visualizer_node]: Setting parameter path_width to 0.200000
[schedule_visualizer_node-4] [INFO] [1689748166.787856287] [schedule_visualizer_node]: Setting parameter initial_map_name to L1
[schedule_visualizer_node-4] [INFO] [1689748166.788106680] [schedule_visualizer_node]: Setting parameter wait_secs to 10
[schedule_visualizer_node-4] [INFO] [1689748166.788346746] [schedule_visualizer_node]: Setting parameter port to 8006
[schedule_visualizer_node-4] [INFO] [1689748166.788623033] [schedule_visualizer_node]: Setting parameter retained_history_count to 50
[navgraph_visualizer_node-7] [INFO] [1689748166.791469729] [navgraph_visualizer]: NavGraph visualizer is running...
[rmf_traffic_schedule-1] [INFO] [1689748166.806320004] [rmf_traffic_schedule_primary]: Beginning traffic schedule node
[rmf_traffic_blockade-2] [INFO] [1689748166.829424974] [rmf_traffic_blockade_node]: Beginning traffic blockade node
[parameter_bridge-18] [INFO] [1689748166.835812261] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/clock (ignition.msgs.Clock) -> /clock (rosgraph_msgs/msg/Clock)] (Lazy 0)
[floorplan_visualizer_node-8] [INFO] [1689748166.849618830] [floorplan_visualizer]: Configuring floorplan_visualizer...
[floorplan_visualizer_node-8] [INFO] [1689748166.850221947] [floorplan_visualizer]: Setting parameter initial_map_name to L1
[rmf_traffic_schedule-1] [INFO] [1689748166.855485601] [rmf_traffic_schedule_primary]: Registered new query [1]
[schedule_visualizer_node-4] [INFO] [1689748166.857132047] [schedule_data_node]: Registering to query topic rmf_traffic/query_update_1
[floorplan_visualizer_node-8] [INFO] [1689748166.861288370] [floorplan_visualizer]: Running floorplan_visualizer...
[schedule_visualizer_node-4] [INFO] [1689748166.862736713] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[rmf_traffic_schedule-1] [INFO] [1689748166.868417511] [rmf_traffic_schedule_primary]: [ScheduleNode::update_mirrors] Sending remedial update starting from the beginning going to 0 for query 1
[schedule_visualizer_node-4] [INFO] [1689748166.875848377] [schedule_visualizer_node]: Successfully connected to rmf_traffic_schedule node.
[schedule_visualizer_node-4] [INFO] [1689748166.876148916] [schedule_data_node]: Mirror handling new sync of 1 queries from schedule node [4a23d806-68a2-40c8-999d-bb779c9af0ee]
[rviz2-10] [INFO] [1689748167.133676795] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-10] [INFO] [1689748167.133780612] [rviz2]: OpenGl version: 4.3 (GLSL 4.3)
[rviz2-10] [INFO] [1689748167.149598454] [rviz2]: Stereo is NOT SUPPORTED
[rmf_visualization_building_systems-6] [INFO] [1689748167.156631372] [building_systems_visualizer]: Building systems visualizer started...
[rmf_visualization_building_systems-6] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: HistoryPolicy.RMW_QOS_POLICY_HISTORY_KEEP_LAST is deprecated. Use HistoryPolicy.KEEP_LAST instead.
[rmf_visualization_building_systems-6]   warnings.warn(
[rmf_visualization_building_systems-6] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_RELIABLE is deprecated. Use ReliabilityPolicy.RELIABLE instead.
[rmf_visualization_building_systems-6]   warnings.warn(
[rmf_visualization_building_systems-6] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[rmf_visualization_building_systems-6]   warnings.warn(
[fleet_adapter-16] [INFO] [1689748167.332488838] [tinyRobot_fleet_adapter]: Parameter [discovery_timeout] set to: 60.000000
[building_map_server-3] [INFO] [1689748167.374740006] [building_map_server]: loading map path: /home/steven/rmf_ws/install/rmf_demos_maps/share/rmf_demos_maps/office/office.building.yaml
[rmf_traffic_schedule-1] [INFO] [1689748167.404316286] [rmf_traffic_schedule_primary]: A new mirror is tracking query ID [1]
[schedule_visualizer_node-4] [INFO] [1689748167.405535107] [schedule_data_node]: Mirror handling new sync of 1 queries from schedule node [4a23d806-68a2-40c8-999d-bb779c9af0ee]
[building_map_server-3] [INFO] [1689748167.406572394] [building_map_server]: opening: /home/steven/rmf_ws/install/rmf_demos_maps/share/rmf_demos_maps/office/office.png
[fleet_adapter-16] [INFO] [1689748167.476217350] [tinyRobot_fleet_adapter]: Registering to query topic rmf_traffic/query_update_1
[simple_api_server-14] Set Server IP to: 0.0.0.0
[simple_api_server-14] Set Server port to: 0.0.0.0:8083
[simple_api_server-14] Set RMF Websocket port to: localhost:7878
[simple_api_server-14] Starting Websocket Server
[simple_api_server-14] Starting RMF_Demos API Server: 0.0.0.0:8083, with ws://localhost:7878
[simple_api_server-14]  * Serving Flask app 'rmf_demos_panel.simple_api_server'
[simple_api_server-14]  * Debug mode: off
[simple_api_server-14] Exception in thread Thread-2 (broadcast_states):
[simple_api_server-14] Traceback (most recent call last):
[simple_api_server-14]   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[simple_api_server-14]     self.run()
[simple_api_server-14]   File "/usr/lib/python3.10/threading.py", line 953, in run
[simple_api_server-14]     self._target(*self._args, **self._kwargs)
[simple_api_server-14]   File "/home/steven/rmf_ws/install/rmf_demos_panel/lib/python3.10/site-packages/rmf_demos_panel/simple_api_server.py", line 135, in broadcast_states
[simple_api_server-14]     socketio.emit('task_status', tasks, broadcast=True, namespace=ns)
[simple_api_server-14]   File "/home/steven/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 462, in emit
[simple_api_server-14]     self.server.emit(event, *args, namespace=namespace, to=to,
[simple_api_server-14] TypeError: Server.emit() got an unexpected keyword argument 'broadcast'
[fleet_adapter-16] [INFO] [1689748167.498405540] [tinyRobot_fleet_adapter]: Mirror handling new sync of 1 queries from schedule node [4a23d806-68a2-40c8-999d-bb779c9af0ee]
[building_map_server-3] [INFO] [1689748167.664720661] [building_map_server]: read 1794169 byte image
[building_map_server-3] [INFO] [1689748167.667444197] [building_map_server]: unable to generate GeoJSON for this map.
[building_map_server-3] [INFO] [1689748167.673138074] [building_map_server]: publishing map...
[building_map_server-3] [INFO] [1689748167.676788510] [building_map_server]: ready to serve map: "building"  Ctrl+C to exit...
[rviz2-10] [INFO] [1689748167.873180664] [rviz2]: Trying to create a map of size 3047 x 1717 using 1 swatches
[rviz2-10] [ERROR] [1689748167.895174145] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-10] active samplers with a different type refer to the same texture image unit
[fleet_adapter-16] [WARN] [1689748168.508710296] [tinyRobot_fleet_adapter]: BroadcastClient unable to connect to [ws://localhost:7878/_internal]. Please make sure server is running. Error msg: invalid state
[fleet_adapter-16] [INFO] [1689748168.512417563] [tinyRobot_fleet_adapter]: BroadcastClient successfully connected to uri: [ws://localhost:7878/_internal]
[fleet_adapter-16] [INFO] [1689748168.536157585] [tinyRobot_command_handle]: Finishing request: [park]
[fleet_adapter-16] [INFO] [1689748168.537103828] [tinyRobot_command_handle]: Fleet [tinyRobot] is configured to perform Loop tasks
[fleet_adapter-16] [INFO] [1689748168.537996826] [tinyRobot_command_handle]: Fleet [tinyRobot] is configured to perform Delivery tasks
[ign-17] [Wrn] [Gui.cc:261] Waited for 10s for a subscriber to [/gazebo/starting_world] and got none.
[ign-17] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/StyleDialog.qml:112:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/StyleDialog.qml:105:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/StyleDialog.qml:98:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] qrc:qml/Main.qml:102:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/PluginMenu.qml:27:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] file::/Gazebo/GazeboDrawer.qml:241:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] file::/Gazebo/GazeboDrawer.qml:147:3: QML Dialog: Binding loop detected for property "implicitHeight"
[ign-17] [GUI] [Wrn] [Application.cc:797] [QT] file::/Gazebo/GazeboDrawer.qml:147:3: QML Dialog: Binding loop detected for property "implicitHeight"
[schedule_visualizer_node-4] [INFO] [1689748186.876305386] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748186.876395210] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[rmf_traffic_schedule-1] [INFO] [1689748186.878453516] [rmf_traffic_schedule_primary]: [ScheduleNode::update_mirrors] Sending remedial update starting from the beginning going to 0 for query 1
[fleet_adapter-16] [INFO] [1689748206.879436528] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748206.879527668] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[schedule_visualizer_node-4] [INFO] [1689748206.880900196] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748206.880979389] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[fleet_adapter-16] [INFO] [1689748226.879452599] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748226.879540619] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[schedule_visualizer_node-4] [INFO] [1689748226.880867552] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748226.880944683] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[rmf_traffic_schedule-1] [INFO] [1689748226.888452624] [rmf_traffic_schedule_primary]: [ScheduleNode::update_mirrors] Sending remedial update starting from the beginning going to 1 for query 1
[schedule_visualizer_node-4] [INFO] [1689748246.888791682] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748246.888879461] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [1]
[fleet_adapter-16] [INFO] [1689748246.889502043] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748246.889595415] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [1]
[schedule_visualizer_node-4] [INFO] [1689748266.888783356] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748266.888873364] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[fleet_adapter-16] [INFO] [1689748266.889455543] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748266.889537987] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[rmf_traffic_schedule-1] [INFO] [1689748266.898430139] [rmf_traffic_schedule_primary]: [ScheduleNode::update_mirrors] Sending remedial update starting from the beginning going to 1 for query 1
[ign-17] [Msg] Ignition Gazebo GUI    v6.14.0
[ign-17] [Dbg] [Gui.cc:253] Waiting for subscribers to [/gazebo/starting_world]...
[ign-17] [Dbg] [Application.cc:92] Initializing application.
[ign-17] [GUI] [Dbg] [Application.cc:555] Create main window
[ign-17] [GUI] [Dbg] [PathManager.cc:66] Requesting resource paths through [/gazebo/resource_paths/get]
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign-17] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[schedule_visualizer_node-4] [INFO] [1689748286.898819439] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748286.898906277] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [1]
[fleet_adapter-16] [INFO] [1689748286.899498702] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748286.899586639] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [1]
[schedule_visualizer_node-4] [INFO] [1689748306.898834110] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748306.898921279] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[fleet_adapter-16] [INFO] [1689748306.899510807] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748306.899611737] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[rmf_traffic_schedule-1] [INFO] [1689748306.908498561] [rmf_traffic_schedule_primary]: [ScheduleNode::update_mirrors] Sending remedial update starting from the beginning going to 2 for query 1
[schedule_visualizer_node-4] [INFO] [1689748326.908930226] [schedule_data_node]: Requesting new schedule update because update timed out
[schedule_visualizer_node-4] [INFO] [1689748326.909027634] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [2]
[fleet_adapter-16] [INFO] [1689748326.909334854] [tinyRobot_fleet_adapter]: Requesting new schedule update because update timed out
[fleet_adapter-16] [INFO] [1689748326.909433983] [tinyRobot_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [2]
``` 

I have started this since yesterday and Gazebo still has not loaded successfully 

### Steps to reproduce the bug

1. Launch the following: ros2 launch rmf_demos_gz_classic office.launch.xml server_uri:="ws://localhost:7878"
2. Rviz loaded and started successfully but not Gazebo

**Comment by aaronchongth** [comment] 2023-07-19 08:52
We haven't been able to reproduce this issue unfortunately, could you provide more information with the questions below:
* what is the hardware you are running on? This could be due to hardware limitations if running on a machine with insufficient resources, CPUs, RAM, etc
* regarding `I have started this since yesterday and Gazebo still has not loaded successfully`, do you mean you kept gazebo in the state below since the day before, and for 12 hours+ it was still stuck there?
![image](https://github.com/open-rmf/rmf/assets/5383623/27aad7a7-dd93-406d-b373-96b0d6666d17)

**Comment by Steven-NYP** [comment] 2023-07-20 09:46
Hi @aaronchongth . Yes I kept gazebo in the state below since the day before and it was still in the same state the next day. I restarted it again and the state remains the same with the same terminal output.

I don't think it's the hardware as I am able to run it successfully in foxy before I upgraded over to humble.

**Comment by aaronchongth** [comment] 2023-07-21 02:34
Hmm, here's how my setup looks and works without issues,

https://github.com/open-rmf/rmf/assets/5383623/a6163996-70f6-48d5-b533-2f2df8f10d61

As a sanity check, could you share the contents of these files of directories (if they exist)? Gists would be appreciated
* `~/.pit_crew/model_cache.json`
* `~/.ignition/fuel/fuel.gazebosim.org/openrobotics/models`
* `~/.gazebo/models`

I have a few more intrusive suggestions to try,

1) reinstall `ignition-fortress`, https://gazebosim.org/docs/fortress/install_ubuntu, do the `rosdep` step again, compile and try again
2) reinstall ROS 2 Humble, do the `rosdep` step again, compile and try again
3) try it on a fresh ubuntu machine, this will be the last resort, as it seems like your system may have been configured to an unrecoverable state that gazebo and ROS 2 can't function well in

**Comment by aaronchongth** [comment] 2023-07-27 07:00
I close this assuming that it has been resolved.

**Closed by aaronchongth** 2023-07-27 07:00 UTC
Labels: bug
